refactor and reformat code

diff --git a/bin/iwant b/bin/iwant
--- a/bin/iwant
+++ b/bin/iwant
@@ -140,84 +140,84 @@ fi
 
 if $is_new; then
 
-show_dialog_template
-TEMPLATE=$(get_dialog_result)
+    show_dialog_template
+    TEMPLATE=$(get_dialog_result)
 
-ASSEMBLYVERSION=1.0.0
-ASSEMBLYVERSIONQUALIFIER=-SNAPSHOT
+    ASSEMBLYVERSION=1.0.0
+    ASSEMBLYVERSIONQUALIFIER=-SNAPSHOT
 
-while true
-do
-    y=
-    show_dialog_artifact_details \
-        "$NAME" "$PACKAGE" "$ASSEMBLYVERSION" "$ASSEMBLYVERSIONQUALIFIER"
-    VALUES=$(get_dialog_result)
-    echo VALUES=$VALUES
-    IFS=$' \n' read -rd '' -a y <<<"$VALUES"
-    #echo array length=${#y[@]} 
-    if (( ${#y[@]} != 4 )); then
-        echo "invalid array length. should be 4."
-        continue
+    while true
+    do
+        y=
+        show_dialog_artifact_details \
+            "$NAME" "$PACKAGE" "$ASSEMBLYVERSION" "$ASSEMBLYVERSIONQUALIFIER"
+        VALUES=$(get_dialog_result)
+        echo VALUES=$VALUES
+        IFS=$' \n' read -rd '' -a y <<<"$VALUES"
+        #echo array length=${#y[@]} 
+        if (( ${#y[@]} != 4 )); then
+            echo "invalid array length. should be 4."
+            continue
+        fi
+        NAME=${y[0]}
+        PACKAGE=${y[1]}
+        ASSEMBLYVERSION=${y[2]}
+        ASSEMBLYVERSIONQUALIFIER=${y[3]}
+        verify_identifier $NAME
+        if (( $? != 0 )); then
+            continue;
+        fi
+        verify_namespace_identifier $PACKAGE
+        if (( $? != 0 )); then
+            continue
+        fi
+        break;
+    done
+
+    if [[ "${TEMPLATE}" == "c#" ]]; then
+        show_dialog_dotnet_framework_version
+        VERSION=$(get_dialog_result)
+
+        show_dialog_output_type
+        TYPE=$(get_dialog_result)
+
+        ARTIFACTEXTENSION=$(resolve_artifact_extension $TYPE)
+
+        PROJECTGUID=`uuidgen | tr '[:lower:]' '[:upper:]'`
+        COMGUID=`uuidgen | tr '[:lower:]' '[:upper:]'`
+        SOLUTIONGUID=`uuidgen | tr '[:lower:]' '[:upper:]'`
     fi
-    NAME=${y[0]}
-    PACKAGE=${y[1]}
-    ASSEMBLYVERSION=${y[2]}
-    ASSEMBLYVERSIONQUALIFIER=${y[3]}
-    verify_identifier $NAME
-    if (( $? != 0 )); then
-        continue;
+
+    TEMPLATEDIR=${IWANT_HOME}/templates/${TEMPLATE}
+    PROJECTNAME=${PACKAGE}.${NAME}
+    FOLDER=${PROJECTNAME}
+
+    if [ ! -d "$TEMPLATEDIR" ]; then
+        echo template ${TEMPLATEDIR} does not exist.
+        exit 1
     fi
-    verify_namespace_identifier $PACKAGE
-    if (( $? != 0 )); then
-        continue
+
+    if [[ "$TEMPLATE" == "java" ]]; then
+        FOLDER=`echo "${FOLDER}" | tr '[:upper:]' '[:lower:]'`
+        PACKAGE=`echo "${PACKAGE}" | tr '[:upper:]' '[:lower:]'`
     fi
-    break;
-done
 
-if [[ "${TEMPLATE}" == "c#" ]]; then
-    show_dialog_dotnet_framework_version
-    VERSION=$(get_dialog_result)
+    if [ -d "$FOLDER" ]; then
+        echo destination ${FOLDER} already exists.
+        exit 1
+    fi
 
-    show_dialog_output_type
-    TYPE=$(get_dialog_result)
+    show_dialog_remote
+    REMOTE=$(get_dialog_result)
 
-    ARTIFACTEXTENSION=$(resolve_artifact_extension $TYPE)
+    echo "using remote ${REMOTE}"
 
-    PROJECTGUID=`uuidgen | tr '[:lower:]' '[:upper:]'`
-    COMGUID=`uuidgen | tr '[:lower:]' '[:upper:]'`
-    SOLUTIONGUID=`uuidgen | tr '[:lower:]' '[:upper:]'`
-fi
+    PRIVATE="true"
 
-TEMPLATEDIR=${IWANT_HOME}/templates/${TEMPLATE}
-PROJECTNAME=${PACKAGE}.${NAME}
-FOLDER=${PROJECTNAME}
-
-if [ ! -d "$TEMPLATEDIR" ]; then
-  echo template ${TEMPLATEDIR} does not exist.
-  exit 1
-fi
-
-if [[ "$TEMPLATE" == "java" ]]; then
-    FOLDER=`echo "${FOLDER}" | tr '[:upper:]' '[:lower:]'`
-    PACKAGE=`echo "${PACKAGE}" | tr '[:upper:]' '[:lower:]'`
-fi
-
-if [ -d "$FOLDER" ]; then
-  echo destination ${FOLDER} already exists.
-  exit 1
-fi
-
-show_dialog_remote
-REMOTE=$(get_dialog_result)
-
-echo "using remote ${REMOTE}"
-
-PRIVATE="true"
-
-if [[ "${REMOTE}" == "git@bitbucket.org" ]]; then
-    show_dialog_public_private
-    PRIVATE=$(get_dialog_result)
-fi
+    if [[ "${REMOTE}" == "git@bitbucket.org" ]]; then
+        show_dialog_public_private
+        PRIVATE=$(get_dialog_result)
+    fi
 
     y=
     while (( ${#y[@]} != 2 ))
@@ -237,6 +237,7 @@ fi
         if (( $? != 0 )); then
             continue;
         fi
+
         verify_identifier $OWNER
         if (( $? != 0 )); then
             continue;
@@ -245,112 +246,116 @@ fi
 
     USEREMAIL=`git config user.email`
 
-REMOTE_URL=${REMOTE}:${OWNER}/${PROJECTNAME}.git
+    REMOTE_URL=${REMOTE}:${OWNER}/${PROJECTNAME}.git
 
-if [[ "${REMOTE}" == "git@bitbucket.org" ]]; then
-    curl \
-        --user ${USERNAME} \
-        https://api.bitbucket.org/1.0/repositories/ \
-        --data name=${PROJECTNAME} \
-        --data has_wiki=true \
-        --data has_issues=true \
-        --data is_private=${PRIVATE} \
-        --data owner=${OWNER}
-    if (( $? != 0 )); then
+    if [[ "${REMOTE}" == "git@bitbucket.org" ]]; then
+        curl \
+            --user ${USERNAME} \
+            https://api.bitbucket.org/1.0/repositories/ \
+            --data name=${PROJECTNAME} \
+            --data has_wiki=true \
+            --data has_issues=true \
+            --data is_private=${PRIVATE} \
+            --data owner=${OWNER}
+        if (( $? != 0 )); then
+            show_dialog "Create Remote Manually" "${REMOTE_URL}"
+        fi
+    else
         show_dialog "Create Remote Manually" "${REMOTE_URL}"
     fi
-else
-    show_dialog "Create Remote Manually" "${REMOTE_URL}"
-fi
 
-cp -R ${TEMPLATEDIR} ${FOLDER}
-cd ${FOLDER}
+    cp -R ${TEMPLATEDIR} ${FOLDER}
+    cd ${FOLDER}
 
-if [[ "${TEMPLATE}" == "c#" ]]; then
-SEDXX='sed 
- -e s/\${AssemblyName}/'${NAME}'/g 
- -e s/\${RootNamespace}/'${PACKAGE}'/g
- -e s/\${TargetFrameworkVersion}/'${VERSION}'/g 
- -e s/\${OutputType}/'${TYPE}'/g
- -e s/\${ArtifactExtension}/'${ARTIFACTEXTENSION}'/g 
- -e s/\${ProjectName}/'${PROJECTNAME}'/g 
- -e s/\${Remote}/'${REMOTE}'/g 
- -e s/\${UserName}/'${USERNAME}'/g 
- -e s/\${Owner}/'${OWNER}'/g 
- -e s/\${UserEmail}/'${USEREMAIL}'/g 
- -e s/\${WebServer}/'${WEBSERVER}'/g 
- -e s/\${ProjectGuid}/'${PROJECTGUID}'/g 
- -e s/\${ComGuid}/'${COMGUID}'/g
- -e s/\${SolutionGuid}/'${SOLUTIONGUID}'/g
- -e s/\${AssemblyVersion}/'${ASSEMBLYVERSION}'/g 
- -e s/\${AssemblyVersionQualifier}/'${ASSEMBLYVERSIONQUALIFIER}'/g'
+    if [[ "${TEMPLATE}" == "c#" ]]; then
+        SEDXX='sed 
+         -e s/\${AssemblyName}/'${NAME}'/g 
+         -e s/\${RootNamespace}/'${PACKAGE}'/g
+         -e s/\${TargetFrameworkVersion}/'${VERSION}'/g 
+         -e s/\${OutputType}/'${TYPE}'/g
+         -e s/\${ArtifactExtension}/'${ARTIFACTEXTENSION}'/g 
+         -e s/\${ProjectName}/'${PROJECTNAME}'/g 
+         -e s/\${Remote}/'${REMOTE}'/g 
+         -e s/\${UserName}/'${USERNAME}'/g 
+         -e s/\${Owner}/'${OWNER}'/g 
+         -e s/\${UserEmail}/'${USEREMAIL}'/g 
+         -e s/\${WebServer}/'${WEBSERVER}'/g 
+         -e s/\${ProjectGuid}/'${PROJECTGUID}'/g 
+         -e s/\${ComGuid}/'${COMGUID}'/g
+         -e s/\${SolutionGuid}/'${SOLUTIONGUID}'/g
+         -e s/\${AssemblyVersion}/'${ASSEMBLYVERSION}'/g 
+         -e s/\${AssemblyVersionQualifier}/'${ASSEMBLYVERSIONQUALIFIER}'/g'
 
-echo using substitution command ${SEDXX}
+        echo using substitution command ${SEDXX}
 
-${SEDXX} App_vs2010.sln > ${PROJECTNAME}_vs2010.sln
-${SEDXX} App.csproj > ${PROJECTNAME}.csproj
-${SEDXX} App.nuspec > ${PROJECTNAME}.nuspec
-${SEDXX} App.cs > ${NAME}.cs
-${SEDXX} AppTests.cs > ${NAME}Tests.cs
-${SEDXX} Properties/AssemblyInfo.cstemplate > Properties/AssemblyInfo.cs
-${SEDXX} pom.xmltemplate > pom.xml
-${SEDXX} config.xmltemplate > config.xml
-${SEDXX} version.txttemplate > version.txt
-${SEDXX} buildsetup.isstemplate > buildsetup.iss
+        ${SEDXX} App_vs2010.sln > ${PROJECTNAME}_vs2010.sln
+        ${SEDXX} App.csproj > ${PROJECTNAME}.csproj
+        ${SEDXX} App.nuspec > ${PROJECTNAME}.nuspec
+        ${SEDXX} App.cs > ${NAME}.cs
+        ${SEDXX} AppTests.cs > ${NAME}Tests.cs
+        ${SEDXX} Properties/AssemblyInfo.cstemplate > Properties/AssemblyInfo.cs
+        ${SEDXX} pom.xmltemplate > pom.xml
+        ${SEDXX} config.xmltemplate > config.xml
+        ${SEDXX} buildsetup.isstemplate > buildsetup.iss
 
-rm App_vs2010.sln
-rm App.csproj
-rm App.nuspec
-rm App.cs
-rm AppTests.cs
-rm Properties/AssemblyInfo.cstemplate
-rm pom.xmltemplate
-rm config.xmltemplate
-rm version.txttemplate
-rm buildsetup.isstemplate
-else
-    ARTIFACTID=`echo "${NAME}" | tr '[:upper:]' '[:lower:]'`
-    PROJECTNAME=`echo "${PROJECTNAME}" | tr '[:upper:]' '[:lower:]'`
-SEDXX='sed 
- -e s/\${AssemblyName}/'${NAME}'/g 
- -e s/\${ArtifactId}/'${ARTIFACTID}'/g
- -e s/\${RootNamespace}/'${PACKAGE}'/g
- -e s/\${ArtifactExtension}/'${ARTIFACTEXTENSION}'/g 
- -e s/\${ProjectName}/'${PROJECTNAME}'/g 
- -e s/\${Remote}/'${REMOTE}'/g 
- -e s/\${UserName}/'${USERNAME}'/g 
- -e s/\${Owner}/'${OWNER}'/g 
- -e s/\${UserEmail}/'${USEREMAIL}'/g 
- -e s/\${WebServer}/'${WEBSERVER}'/g 
- -e s/\${AssemblyVersion}/'${ASSEMBLYVERSION}'/g 
- -e s/\${AssemblyVersionQualifier}/'${ASSEMBLYVERSIONQUALIFIER}'/g'
+        rm App_vs2010.sln
+        rm App.csproj
+        rm App.nuspec
+        rm App.cs
+        rm AppTests.cs
+        rm Properties/AssemblyInfo.cstemplate
+        rm pom.xmltemplate
+        rm config.xmltemplate
+        rm buildsetup.isstemplate
 
-echo using substitution command ${SEDXX}
+        # CREATE local .iwant folder
+        mkdir .iwant
+        echo ${PROJECTNAME}>.iwant/projectname.txt
+        echo ${REMOTE}:${OWNER}>.iwant/repository.txt
+        echo ${ASSEMBLYVERSION}${ASSEMBLYVERSIONQUALIFIER}>.iwant/version.txt
+    else
+        ARTIFACTID=`echo "${NAME}" | tr '[:upper:]' '[:lower:]'`
+        PROJECTNAME=`echo "${PROJECTNAME}" | tr '[:upper:]' '[:lower:]'`
+        SEDXX='sed 
+         -e s/\${AssemblyName}/'${NAME}'/g 
+         -e s/\${ArtifactId}/'${ARTIFACTID}'/g
+         -e s/\${RootNamespace}/'${PACKAGE}'/g
+         -e s/\${ArtifactExtension}/'${ARTIFACTEXTENSION}'/g 
+         -e s/\${ProjectName}/'${PROJECTNAME}'/g 
+         -e s/\${Remote}/'${REMOTE}'/g 
+         -e s/\${UserName}/'${USERNAME}'/g 
+         -e s/\${Owner}/'${OWNER}'/g 
+         -e s/\${UserEmail}/'${USEREMAIL}'/g 
+         -e s/\${WebServer}/'${WEBSERVER}'/g 
+         -e s/\${AssemblyVersion}/'${ASSEMBLYVERSION}'/g 
+         -e s/\${AssemblyVersionQualifier}/'${ASSEMBLYVERSIONQUALIFIER}'/g'
 
-    AUXPATH0=`echo "${PACKAGE}" | tr . /`
-    AUXPATH=`echo "${AUXPATH0}" | tr '[:upper:]' '[:lower:]'`
-    ${SEDXX} App.java > ${NAME}.java
-    ${SEDXX} AppTest.java > ${NAME}Test.java
-    ${SEDXX} pom.xmltemplate > pom.xml
-    ${SEDXX} config.xmltemplate > config.xml
-    ${SEDXX} release.xmltemplate > release.xml
-    ${SEDXX} cover.shtemplate > cover.sh
-    mkdir -p src/main/java/$AUXPATH
-    mkdir -p src/test/java/$AUXPATH
-    mv ${NAME}.java src/main/java/$AUXPATH
-    mv ${NAME}Test.java src/test/java/$AUXPATH
-    rm App.java
-    rm AppTest.java
-    rm pom.xmltemplate
-    rm config.xmltemplate
-    rm release.xmltemplate
-    rm cover.shtemplate
-    chmod +x cover.sh
-fi
+        echo using substitution command ${SEDXX}
 
-git init
-git add --all
-git commit -m "Initial commit"
+        AUXPATH0=`echo "${PACKAGE}" | tr . /`
+        AUXPATH=`echo "${AUXPATH0}" | tr '[:upper:]' '[:lower:]'`
+        ${SEDXX} App.java > ${NAME}.java
+        ${SEDXX} AppTest.java > ${NAME}Test.java
+        ${SEDXX} pom.xmltemplate > pom.xml
+        ${SEDXX} config.xmltemplate > config.xml
+        ${SEDXX} release.xmltemplate > release.xml
+        ${SEDXX} cover.shtemplate > cover.sh
+        mkdir -p src/main/java/$AUXPATH
+        mkdir -p src/test/java/$AUXPATH
+        mv ${NAME}.java src/main/java/$AUXPATH
+        mv ${NAME}Test.java src/test/java/$AUXPATH
+        rm App.java
+        rm AppTest.java
+        rm pom.xmltemplate
+        rm config.xmltemplate
+        rm release.xmltemplate
+        rm cover.shtemplate
+        chmod +x cover.sh
+    fi
+
+    git init
+    git add --all
+    git commit -m "Initial commit"
 
     git remote add origin ${REMOTE_URL}
     verify_cancel $?
@@ -360,29 +365,32 @@ else
 fi
 # end if is_new
 
-    git push -u origin --all
-    if (( $? != 0 )); then
-        show_dialog "please do a manual push and press ok"
-    fi
+git push -u origin --all
+if (( $? != 0 )); then
+    show_dialog "please do a manual push and press ok"
+fi
+
+curl \
+    -X POST \
+    "${JENKINS_URL}/createItem?name=${PROJECTNAME}" \
+    --data-binary "@config.xml" \
+    -H "Content-Type: text/xml"
+verify_cancel $?
+
+curl \
+    -X POST \
+    "${JENKINS_URL}/job/${PROJECTNAME}/template/config.xml" \
+    --data-binary "@detail.xml" \
+    -H "Content-Type: text/xml"
+verify_cancel $?
+
+if [[ "${TEMPLATE}" == "c#" ]]; then
+    echo "release job not needed for now..."
+else
     curl \
         -X POST \
-        "${JENKINS_URL}/createItem?name=${PROJECTNAME}" \
-        --data-binary "@config.xml" \
+        "${JENKINS_URL}/createItem?name=RELEASE_${PROJECTNAME}" \
+        --data-binary "@release.xml" \
         -H "Content-Type: text/xml"
     verify_cancel $?
-    curl \
-        -X POST \
-        "${JENKINS_URL}/job/${PROJECTNAME}/template/config.xml" \
-        --data-binary "@detail.xml" \
-        -H "Content-Type: text/xml"
-    verify_cancel $?
-    if [[ "${TEMPLATE}" == "c#" ]]; then
-        echo "release job not needed for now..."
-    else
-        curl \
-            -X POST \
-            "${JENKINS_URL}/createItem?name=RELEASE_${PROJECTNAME}" \
-            --data-binary "@release.xml" \
-            -H "Content-Type: text/xml"
-        verify_cancel $?
-    fi
+fi
